//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWWebPage.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MWWebPage.Resources.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD.
        /// </summary>
        public static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add from wardrobe.
        /// </summary>
        public static string addFromMW {
            get {
                return ResourceManager.GetString("addFromMW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD PICTURE.
        /// </summary>
        public static string addFromPC {
            get {
                return ResourceManager.GetString("addFromPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account?.
        /// </summary>
        public static string alreadyUser {
            get {
                return ResourceManager.GetString("alreadyUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Don&apos;t ask  me any more, always put them in this folder.
        /// </summary>
        public static string askNoMore {
            get {
                return ResourceManager.GetString("askNoMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TokenExpired.
        /// </summary>
        public static string badToken {
            get {
                return ResourceManager.GetString("badToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        public static string birthday {
            get {
                return ResourceManager.GetString("birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        public static string brand {
            get {
                return ResourceManager.GetString("brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand Down.
        /// </summary>
        public static string brandDown {
            get {
                return ResourceManager.GetString("brandDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand Up.
        /// </summary>
        public static string brandUp {
            get {
                return ResourceManager.GetString("brandUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you a business or designer?.
        /// </summary>
        public static string busOrDes {
            get {
                return ResourceManager.GetString("busOrDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business &amp; Design.
        /// </summary>
        public static string bussineAndDesign {
            get {
                return ResourceManager.GetString("bussineAndDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCEL.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADDTO.
        /// </summary>
        public static string capAdd {
            get {
                return ResourceManager.GetString("capAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALL.
        /// </summary>
        public static string capAll {
            get {
                return ResourceManager.GetString("capAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BRANDS.
        /// </summary>
        public static string capBrand {
            get {
                return ResourceManager.GetString("capBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BUDGET.
        /// </summary>
        public static string capBudget {
            get {
                return ResourceManager.GetString("capBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CATEGORIES.
        /// </summary>
        public static string capCategory {
            get {
                return ResourceManager.GetString("capCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLEAR.
        /// </summary>
        public static string capClear {
            get {
                return ResourceManager.GetString("capClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COLOR.
        /// </summary>
        public static string capColor {
            get {
                return ResourceManager.GetString("capColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE.
        /// </summary>
        public static string capDelete {
            get {
                return ResourceManager.GetString("capDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DONE.
        /// </summary>
        public static string capDone {
            get {
                return ResourceManager.GetString("capDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOVE TO.
        /// </summary>
        public static string capMoveTo {
            get {
                return ResourceManager.GetString("capMoveTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECTED.
        /// </summary>
        public static string capSelected {
            get {
                return ResourceManager.GetString("capSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAGS.
        /// </summary>
        public static string capTag {
            get {
                return ResourceManager.GetString("capTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPLOAD.
        /// </summary>
        public static string capUpload {
            get {
                return ResourceManager.GetString("capUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Down.
        /// </summary>
        public static string catDown {
            get {
                return ResourceManager.GetString("catDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string category {
            get {
                return ResourceManager.GetString("category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Up.
        /// </summary>
        public static string catUp {
            get {
                return ResourceManager.GetString("catUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string change {
            get {
                return ResourceManager.GetString("change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANGE PICTURE.
        /// </summary>
        public static string changePic {
            get {
                return ResourceManager.GetString("changePic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中文.
        /// </summary>
        public static string chinese {
            get {
                return ResourceManager.GetString("chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a Tag.
        /// </summary>
        public static string chooseTag {
            get {
                return ResourceManager.GetString("chooseTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string comment {
            get {
                return ResourceManager.GetString("comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string confirm {
            get {
                return ResourceManager.GetString("confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create My Wardrobe.
        /// </summary>
        public static string createAccount {
            get {
                return ResourceManager.GetString("createAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE A NEW TAG.
        /// </summary>
        public static string createNewTag {
            get {
                return ResourceManager.GetString("createNewTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string day {
            get {
                return ResourceManager.GetString("day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISCOUNT.
        /// </summary>
        public static string discount {
            get {
                return ResourceManager.GetString("discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discription.
        /// </summary>
        public static string discription {
            get {
                return ResourceManager.GetString("discription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIT.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to incorrect format.
        /// </summary>
        public static string emailError {
            get {
                return ResourceManager.GetString("emailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string english {
            get {
                return ResourceManager.GetString("english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        public static string enter {
            get {
                return ResourceManager.GetString("enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXPLORE.
        /// </summary>
        public static string explore {
            get {
                return ResourceManager.GetString("explore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget my password.
        /// </summary>
        public static string forgetPassword {
            get {
                return ResourceManager.GetString("forgetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string forgetPwd {
            get {
                return ResourceManager.GetString("forgetPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GENDER.
        /// </summary>
        public static string gender {
            get {
                return ResourceManager.GetString("gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string genderFemale {
            get {
                return ResourceManager.GetString("genderFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string genderMale {
            get {
                return ResourceManager.GetString("genderMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        public static string genderSelected {
            get {
                return ResourceManager.GetString("genderSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Center.
        /// </summary>
        public static string helpCenter {
            get {
                return ResourceManager.GetString("helpCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By clicking &apos;create&apos;, you agree to our.
        /// </summary>
        public static string hitCreateAccount {
            get {
                return ResourceManager.GetString("hitCreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and that you have read our.
        /// </summary>
        public static string hitRead {
            get {
                return ResourceManager.GetString("hitRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string image {
            get {
                return ResourceManager.GetString("image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string index {
            get {
                return ResourceManager.GetString("index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string input {
            get {
                return ResourceManager.GetString("input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instruction.
        /// </summary>
        public static string instruction {
            get {
                return ResourceManager.GetString("instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn More .
        /// </summary>
        public static string learnMore {
            get {
                return ResourceManager.GetString("learnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIST.
        /// </summary>
        public static string list {
            get {
                return ResourceManager.GetString("list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string location {
            get {
                return ResourceManager.GetString("location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melbource.
        /// </summary>
        public static string locationMel {
            get {
                return ResourceManager.GetString("locationMel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to incorrect email or password.
        /// </summary>
        public static string loginError {
            get {
                return ResourceManager.GetString("loginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  MEGAWARDROBE.
        /// </summary>
        public static string logo {
            get {
                return ResourceManager.GetString("logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGOUT.
        /// </summary>
        public static string logOut {
            get {
                return ResourceManager.GetString("logOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mon.
        /// </summary>
        public static string month {
            get {
                return ResourceManager.GetString("month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OutFit.
        /// </summary>
        public static string mwOutFit {
            get {
                return ResourceManager.GetString("mwOutFit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Item.
        /// </summary>
        public static string mwSingleItem {
            get {
                return ResourceManager.GetString("mwSingleItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        public static string nationality {
            get {
                return ResourceManager.GetString("nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string newed {
            get {
                return ResourceManager.GetString("newed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEWEST.
        /// </summary>
        public static string newest {
            get {
                return ResourceManager.GetString("newest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string next {
            get {
                return ResourceManager.GetString("next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nick Name.
        /// </summary>
        public static string nickName {
            get {
                return ResourceManager.GetString("nickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTIFICATION.
        /// </summary>
        public static string notification {
            get {
                return ResourceManager.GetString("notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupation.
        /// </summary>
        public static string occupation {
            get {
                return ResourceManager.GetString("occupation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old.
        /// </summary>
        public static string old {
            get {
                return ResourceManager.GetString("old", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string other {
            get {
                return ResourceManager.GetString("other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password too short.
        /// </summary>
        public static string passwordTooShort {
            get {
                return ResourceManager.GetString("passwordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy.
        /// </summary>
        public static string policy {
            get {
                return ResourceManager.GetString("policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Down.
        /// </summary>
        public static string priceDown {
            get {
                return ResourceManager.GetString("priceDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Up.
        /// </summary>
        public static string priceUp {
            get {
                return ResourceManager.GetString("priceUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string privacy {
            get {
                return ResourceManager.GetString("privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy &amp; Terms.
        /// </summary>
        public static string privacyAndTerms {
            get {
                return ResourceManager.GetString("privacyAndTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANGE.
        /// </summary>
        public static string proChange {
            get {
                return ResourceManager.GetString("proChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROFILE.
        /// </summary>
        public static string profile {
            get {
                return ResourceManager.GetString("profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HELP.
        /// </summary>
        public static string proHelp {
            get {
                return ResourceManager.GetString("proHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTING.
        /// </summary>
        public static string proSetting {
            get {
                return ResourceManager.GetString("proSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prsnl Center.
        /// </summary>
        public static string PrsnlCenter {
            get {
                return ResourceManager.GetString("PrsnlCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase.
        /// </summary>
        public static string purchase {
            get {
                return ResourceManager.GetString("purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECOMMAND.
        /// </summary>
        public static string recommand {
            get {
                return ResourceManager.GetString("recommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Keep me signed in..
        /// </summary>
        public static string rememberMe {
            get {
                return ResourceManager.GetString("rememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string reset {
            get {
                return ResourceManager.GetString("reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVE.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scene.
        /// </summary>
        public static string scene {
            get {
                return ResourceManager.GetString("scene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string share {
            get {
                return ResourceManager.GetString("share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shot.
        /// </summary>
        public static string shot {
            get {
                return ResourceManager.GetString("shot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find your fasion around you..
        /// </summary>
        public static string slogen {
            get {
                return ResourceManager.GetString("slogen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOCIAL NETWORK.
        /// </summary>
        public static string sn {
            get {
                return ResourceManager.GetString("sn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login with Social Network.
        /// </summary>
        public static string snwLogin {
            get {
                return ResourceManager.GetString("snwLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort By.
        /// </summary>
        public static string sort {
            get {
                return ResourceManager.GetString("sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string source {
            get {
                return ResourceManager.GetString("source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get started here..
        /// </summary>
        public static string startHere {
            get {
                return ResourceManager.GetString("startHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stylepallet.
        /// </summary>
        public static string stylePallet {
            get {
                return ResourceManager.GetString("stylePallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string test {
            get {
                return ResourceManager.GetString("test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login With.
        /// </summary>
        public static string thirdLogin {
            get {
                return ResourceManager.GetString("thirdLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string time {
            get {
                return ResourceManager.GetString("time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the token is expired, please redo the process.
        /// </summary>
        public static string tokenExpired {
            get {
                return ResourceManager.GetString("tokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wardrobe.
        /// </summary>
        public static string wardrobe {
            get {
                return ResourceManager.GetString("wardrobe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string year {
            get {
                return ResourceManager.GetString("year", resourceCulture);
            }
        }
    }
}
